-- Tabla TRANSACTIONS
CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    UUID TEXT NOT NULL UNIQUE,
    DATETIME TEXT NOT NULL,
    YEAR INTEGER NOT NULL,
    MONTH INTEGER NOT NULL,
    TYPE TEXT NOT NULL,
    AMOUNT INTEGER NOT NULL,
    CURRENCY TEXT NOT NULL DEFAULT 'ARS',
    CATEGORY TEXT NOT NULL,
    DESCRIPTION TEXT,
    AFFECTS_LIQUIDITY INTEGER NOT NULL CHECK (AFFECTS_LIQUIDITY IN (0,1))
);

-- Índices para TRANSACTIONS
CREATE INDEX IF NOT EXISTS idx_transactions_year_month ON TRANSACTIONS(YEAR, MONTH);
CREATE INDEX IF NOT EXISTS idx_transactions_type_year_month ON TRANSACTIONS(TYPE, YEAR, MONTH);
CREATE INDEX IF NOT EXISTS idx_transactions_currency_year_month ON TRANSACTIONS(CURRENCY, YEAR, MONTH);
CREATE INDEX IF NOT EXISTS idx_transactions_datetime ON TRANSACTIONS(DATETIME);

-- Tabla LIQUIDITY_OPENING_BALANCE
CREATE TABLE IF NOT EXISTS LIQUIDITY_OPENING_BALANCE (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DATETIME TEXT NOT NULL,
    CURRENCY TEXT NOT NULL DEFAULT 'ARS',
    AMOUNT INTEGER NOT NULL,
    DESCRIPTION TEXT
);

-- Índice para LIQUIDITY_OPENING_BALANCE
CREATE INDEX IF NOT EXISTS idx_liquidity_currency ON LIQUIDITY_OPENING_BALANCE(CURRENCY);

-- Tabla CARD_STATEMENTS
CREATE TABLE IF NOT EXISTS CARD_STATEMENTS (
    UUID TEXT PRIMARY KEY,
    YEAR INTEGER NOT NULL,
    MONTH INTEGER NOT NULL,
    CARD_TYPE TEXT NOT NULL,
    FILENAME TEXT NOT NULL,
    AMOUNT_ARS INTEGER NOT NULL DEFAULT 0,
    AMOUNT_USD INTEGER NOT NULL DEFAULT 0,
    CONVERSION_AMOUNT INTEGER NOT NULL,
    TOTAL_AMOUNT_ARS INTEGER NOT NULL,
    AMOUNT_TOTAL_ARS INTEGER NOT NULL DEFAULT 0,
    DATETIME TEXT NOT NULL,
    -- Campos para debug del cálculo del dólar tarjeta
    TOTAL_USD REAL,
    BASE_PESOS REAL,
    FX_BASE REAL,
    FACTOR_IMPUESTOS REAL
);

-- Índices para CARD_STATEMENTS
CREATE INDEX IF NOT EXISTS idx_card_statements_year_month ON CARD_STATEMENTS(YEAR, MONTH);
CREATE INDEX IF NOT EXISTS idx_card_statements_card_type_year_month ON CARD_STATEMENTS(CARD_TYPE, YEAR, MONTH);

-- Tabla CARD_STATEMENT_ITEMS
CREATE TABLE IF NOT EXISTS CARD_STATEMENT_ITEMS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    UUID TEXT NOT NULL,
    POSITION INTEGER NOT NULL,
    AMOUNT_ARS INTEGER NOT NULL DEFAULT 0,
    AMOUNT_USD INTEGER NOT NULL DEFAULT 0,
    HOLDER TEXT NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    IS_CUOTA INTEGER NOT NULL DEFAULT 0 CHECK (IS_CUOTA IN (0,1)),
    DATE_STRING TEXT,
    DATETIME TEXT,
    FOREIGN KEY (UUID) REFERENCES CARD_STATEMENTS(UUID) ON DELETE CASCADE,
    UNIQUE (UUID, POSITION)
);

-- Índices para CARD_STATEMENT_ITEMS
CREATE INDEX IF NOT EXISTS idx_card_items_uuid ON CARD_STATEMENT_ITEMS(UUID);
CREATE INDEX IF NOT EXISTS idx_card_items_holder ON CARD_STATEMENT_ITEMS(HOLDER);
CREATE INDEX IF NOT EXISTS idx_card_items_is_cuota ON CARD_STATEMENT_ITEMS(IS_CUOTA);

-- Tabla PATRIMONIO
CREATE TABLE IF NOT EXISTS PATRIMONIO (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TYPE TEXT NOT NULL CHECK (TYPE IN ('BITCOIN', 'CEDEAR', 'PATRIMONIO_USD', 'USD_FISICO')),
    QUANTITY REAL,  -- Para Bitcoin y CEDEAR (cantidad de unidades)
    VALUE_USD INTEGER,  -- Para patrimonio en USD (en centavos de USD)
    DESCRIPTION TEXT,  -- Para patrimonio en USD (ej: "Auto")
    DATETIME TEXT NOT NULL,
    ACTIVE INTEGER NOT NULL DEFAULT 1 CHECK (ACTIVE IN (0,1))
);

-- Índices para PATRIMONIO
CREATE INDEX IF NOT EXISTS idx_patrimonio_type ON PATRIMONIO(TYPE);
CREATE INDEX IF NOT EXISTS idx_patrimonio_active ON PATRIMONIO(ACTIVE);

-- Tabla CEDEAR_QUOTES
CREATE TABLE IF NOT EXISTS CEDEAR_QUOTES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TICKER TEXT NOT NULL,
    DATE TEXT NOT NULL,
    DATA TEXT NOT NULL,  -- JSON completo de la cotización
    DATETIME TEXT NOT NULL,
    UNIQUE(TICKER, DATE)
);

-- Índices para CEDEAR_QUOTES
CREATE INDEX IF NOT EXISTS idx_cedear_quotes_ticker_date ON CEDEAR_QUOTES(TICKER, DATE);
CREATE INDEX IF NOT EXISTS idx_cedear_quotes_date ON CEDEAR_QUOTES(DATE);
